image: registry.gitlab.com/nplustech/php-pipeline

stages:
  - syntax
  - build
  - test

variables:
  KTPAYAPI_APP_KEY: $CI_JOB_APP_KEY
  KTPAYAPI_KEY: $CI_JOB_KEY

Verifying code syntax:
  stage: syntax
  script:
    - phpcs --extensions=php -n --standard=PSR2 --encoding=utf-8 src/
    #- git show --pretty="" --name-only $CI_COMMIT_SHA | grep "^ [MAC] .*\.php" | awk '{print $2}'

Building library:
  stage: build
  script:
    - composer install

Testing library:
  stage: test
  script:
    - ./vendor/bin/phpunit --coverage-text --colors=never

cache:
  paths:
    - vendor/