image: registry.gitlab.com/nplustech/php-pipeline

stages:
  - syntax
  - build
  - test

variables:
  KTPAYAPI_APP_KEY: $CI_JOB_APP_KEY
  KTPAYAPI_KEY: $CI_JOB_KEY

code_quality:
  stage: syntax
  script:
    - phpcs --report=full --extensions=php -n --standard=PSR2 --encoding=utf-8 src/
  allow_failure: true

Building library:
  stage: build
  script:
    - composer install

Testing library:
  stage: test
  script:
    - ./vendor/bin/phpunit --coverage-text --colors=never

cache:
  paths:
    - vendor/